
# $FreeBSD: soc2013/dpl/head/sys/modules/pps/Makefile 122937 2003-11-19 05:08:27Z imp $

.PATH:	${.CURDIR}/../../dev/ppbus
KMOD=	pps
SRCS=	bus_if.h device_if.h ppbus_if.h \
	pps.c

.include <bsd.kmod.mk>
