# $FreeBSD: soc2013/dpl/head/sys/modules/sis/Makefile 181567 2008-08-10 10:00:14Z imp $

.PATH: ${.CURDIR}/../../dev/sis

KMOD=	if_sis
SRCS=	if_sis.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h

.include <bsd.kmod.mk>
