# $FreeBSD: soc2013/dpl/head/etc/namedb/Makefile 170956 2007-06-18 05:44:38Z dougb $

SUBDIR=	master

FILES=	named.conf named.root

NO_OBJ=
FILESDIR=	/etc/namedb
FILESMODE=	644

.include <bsd.prog.mk>
