# $FreeBSD: soc2013/dpl/head/sys/modules/i2c/controllers/amdsmb/Makefile 153661 2005-12-21 15:49:51Z ru $

.PATH: ${.CURDIR}/../../../../pci

KMOD=	amdsmb
SRCS=	amdsmb.c
SRCS+=	device_if.h smbus_if.h pci_if.h bus_if.h

.include <bsd.kmod.mk>
