# $FreeBSD: soc2013/dpl/head/usr.sbin/bsdinstall/Makefile 223138 2011-06-11 21:44:07Z nwhitehorn $

SUBDIR= distextract distfetch partedit scripts
SCRIPTS= bsdinstall
MAN= bsdinstall.8

.include <bsd.prog.mk>
