#
# $FreeBSD: soc2013/dpl/head/tools/regression/environ/Makefile.retention 171238 2007-07-04 00:00:41Z scf $
#
SRCS=	retention.c
PROG=	retention

CFLAGS+=-Wall -I../../../include

CLEANFILES=	*~ ${PROG}.core

NO_MAN=	yes

.include <bsd.prog.mk>

test: ${PROG}
	@./${PROG}
