# $FreeBSD: soc2013/dpl/head/usr.sbin/sysrc/Makefile 247747 2013-02-08 11:14:01Z dteske $

SCRIPTS= sysrc

MAN= sysrc.8

beforeinstall:
	mkdir -p ${DESTDIR}${SCRIPTSDIR}
	mkdir -p ${DESTDIR}${MANDIR}8

.include <bsd.prog.mk>
