# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/warp/Makefile 106805 2002-11-11 10:11:59Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/warp

KMOD=	warp_saver
SRCS=	warp_saver.c

.include <bsd.kmod.mk>
