# $FreeBSD: soc2013/dpl/head/sys/modules/ata/atacbus/Makefile 252320 2013-05-29 23:56:49Z marius $

.PATH: ${.CURDIR}/../../../dev/ata

KMOD=	atacbus
SRCS=	ata-cbus.c
SRCS+=	ata_if.h bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
