# $FreeBSD: soc2013/dpl/head/lib/clang/libllvmobject/Makefile 252879 2013-06-12 18:48:53Z dim $

.include <bsd.own.mk>

LIB=	llvmobject

SRCDIR=	lib/Object
SRCS=	Archive.cpp \
	Binary.cpp \
	COFFObjectFile.cpp \
	ELFObjectFile.cpp \
	Error.cpp \
	MachOObjectFile.cpp \
	Object.cpp \
	ObjectFile.cpp

.include "../clang.lib.mk"
