# $FreeBSD: soc2013/dpl/head/sys/modules/sound/driver/spicds/Makefile 162935 2006-09-30 18:12:33Z netchild $

.PATH: ${.CURDIR}/../../../../dev/sound/pci

KMOD=	snd_spicds
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h
SRCS+=	spicds.c

.include <bsd.kmod.mk>
