# $FreeBSD: soc2013/dpl/head/cddl/usr.sbin/dtruss/Makefile 211884 2010-08-26 11:45:39Z rpaulo $

.PATH: ${.CURDIR}/../../../cddl/contrib/dtracetoolkit

SCRIPTS=dtruss
MAN=dtruss.1

.include <bsd.prog.mk>
