# $FreeBSD: soc2013/dpl/head/lib/clang/libllvmarchive/Makefile 247460 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvmarchive

SRCDIR=	lib/Archive
SRCS=	Archive.cpp \
	ArchiveReader.cpp \
	ArchiveWriter.cpp

.include "../clang.lib.mk"
