# $FreeBSD: soc2013/dpl/head/sys/modules/cc/cc_chd/Makefile 218198 2011-02-01 07:05:14Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_chd
SRCS=	cc_chd.c

.include <bsd.kmod.mk>
