# $FreeBSD: soc2013/dpl/head/sys/modules/ucycom/Makefile 139442 2004-12-29 08:50:35Z imp $

S=	${.CURDIR}/../..
.PATH: $S/dev/usb

KMOD=	ucycom
SRCS=	ucycom.c opt_usb.h device_if.h bus_if.h usbdevs.h

.include <bsd.kmod.mk>
