# $FreeBSD: soc2013/dpl/head/sys/modules/geom/geom_sunlabel/Makefile 115522 2003-05-31 18:36:41Z phk $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_sunlabel
SRCS=	geom_sunlabel.c geom_sunlabel_enc.c

.include <bsd.kmod.mk>
