#
# $FreeBSD: soc2013/dpl/head/tools/regression/netinet/tcpsockclosebeforeaccept/Makefile 160245 2006-07-09 11:51:14Z maxim $
#

PROG=	tcpsockclosebeforeaccept
NO_MAN=
WARNS?=	3

.include <bsd.prog.mk>
