#	$FreeBSD: soc2013/dpl/head/libexec/tftp-proxy/Makefile 201423 2010-01-02 09:50:19Z ed $

.PATH:	${.CURDIR}/../../contrib/pf/tftp-proxy

PROG=	tftp-proxy
SRCS=	tftp-proxy.c filter.c
MAN=	tftp-proxy.8

WARNS?=	3

.include <bsd.prog.mk>
