# $FreeBSD: soc2013/dpl/head/sys/modules/vge/Makefile 150679 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/vge

KMOD=	if_vge
SRCS=	if_vge.c miibus_if.h device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
