# Makefile for ntpd.
# $FreeBSD: soc2013/dpl/head/usr.sbin/ntp/Makefile 200620 2009-12-15 14:59:58Z roberto $

SUBDIR=	libopts libntp libparse ntpd ntpdc ntpq ntpdate \
	ntptime ntp-keygen sntp
SUBDIR+=	doc

.include <bsd.subdir.mk>
