# $FreeBSD: soc2013/dpl/head/sys/modules/mxge/mxge_eth_z8e/Makefile 171543 2007-07-19 16:16:00Z gallatin $

.PATH: ${.CURDIR}/../../../dev/mxge
KMOD=	mxge_eth_z8e
SRCS=	mxge_eth_z8e.c

.include <bsd.kmod.mk>
