# $FreeBSD: soc2013/dpl/head/share/i18n/esdb/EBCDIC/Makefile 219062 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.4 2008/10/25 22:27:36 apb Exp $

CODE=	EBCDIC
SED_EXP= 's/EBCDIC-x/EBCDIC-%%PART%%/'

.include "../Makefile.part"
