# $FreeBSD: soc2013/dpl/head/lib/clang/libllvmirreader/Makefile 250624 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmirreader

SRCDIR=	lib/IRReader
SRCS=	IRReader.cpp

.include "../clang.lib.mk"
