# $FreeBSD: soc2013/dpl/head/usr.sbin/bsdconfig/timezone/include/Makefile 241856 2012-09-18 22:28:42Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/090.timezone/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
