# $Id: Makefile,v 1.2 2000/07/14 18:16:25 iwasaki Exp $
# $FreeBSD: soc2013/dpl/head/usr.sbin/acpi/acpiconf/Makefile 201433 2010-01-02 11:07:44Z ed $

PROG=	acpiconf
MAN=	acpiconf.8

.include <bsd.prog.mk>
