# $FreeBSD: soc2013/dpl/head/sys/modules/geom/geom_vol_ffs/Makefile 115826 2003-06-03 20:32:13Z gordon $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_vol_ffs
SRCS=	geom_vol_ffs.c

.include <bsd.kmod.mk>
