# $FreeBSD: soc2013/dpl/head/sys/modules/digi/digi_Xe/Makefile 76236 2001-05-02 01:08:09Z brian $

.PATH:	${.CURDIR}/../../../dev/digi
KMOD=	digi_Xe
SRCS=	Xe.c Xe.bios.h Xe.fepos.h digi_mod.h

.include <bsd.kmod.mk>
