#
# $FreeBSD: soc2013/dpl/head/tools/regression/netipx/ipxdgramloopback/Makefile 204354 2010-02-25 14:42:26Z ru $
#

PROG=	ipxdgramloopback
NO_MAN=

DPADD=	${LIBIPX}
LDADD=	-lipx
WARNS?=	3

.include <bsd.prog.mk>
