# $FreeBSD: soc2013/dpl/head/share/i18n/esdb/Makefile.inc 219062 2011-02-25 00:04:39Z gabor $

.PATH: ${.CURDIR}

ESDBDIR?= /usr/share/i18n/esdb
MKESDB?= ${.OBJDIR}/../../../usr.bin/mkesdb_static/mkesdb_static
