# $FreeBSD: soc2013/dpl/head/sys/modules/ie/Makefile 140910 2005-01-26 16:29:07Z imp $
#

.PATH:	${.CURDIR}/../../dev/ie

KMOD=	if_ie
SRCS=	if_ie.c if_ie_isa.c \
	isa_if.h bus_if.h device_if.h
WERROR=

.include <bsd.kmod.mk>
