# $FreeBSD: soc2013/dpl/head/lib/libiconv_modules/EUCTW/Makefile 219062 2011-02-25 00:04:39Z gabor $

SHLIB=	EUCTW
SRCS+=	citrus_euctw.c
CFLAGS+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
