#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: soc2013/dpl/head/sbin/dumpfs/Makefile 198279 2009-10-19 16:00:24Z ru $

PROG=	dumpfs
WARNS?=	2
DPADD=	${LIBUFS}
LDADD=	-lufs
MAN=	dumpfs.8

.include <bsd.prog.mk>
