# $FreeBSD: soc2013/dpl/head/tools/tools/net80211/wlanstats/Makefile 161243 2006-08-10 19:01:16Z sam $

PROG=	wlanstats
BINDIR=	/usr/local/bin
NO_MAN=

SRCS=	statfoo.c wlanstats.c main.c

.include <bsd.prog.mk>
