# Makefile for building the sample syscall module
# $FreeBSD: soc2013/dpl/head/share/examples/kld/syscall/module/Makefile 83649 2001-09-18 12:03:42Z ru $

KMOD=	syscall
SRCS=	syscall.c

.include <bsd.kmod.mk>
