# $FreeBSD: soc2013/dpl/head/usr.sbin/nandsim/Makefile 235866 2012-05-17 10:11:18Z gber $

PROG=	nandsim
SRCS=	nandsim.c nandsim_rcfile.c nandsim_cfgparse.c
BINDIR=	/usr/sbin
MAN=	nandsim.8

.include <bsd.prog.mk>
