#	@(#)Makefile	8.1 (Berkeley) 3/31/94
# $FreeBSD: soc2013/dpl/head/games/random/Makefile 203966 2010-02-15 14:32:00Z uqs $

PROG=	random
MAN=	random.6
SRCS=	random.c randomize_fd.c

.include <bsd.prog.mk>
