# $FreeBSD: soc2013/dpl/head/sys/boot/sparc64/zfsloader/Makefile 235197 2012-05-01 17:16:01Z marius $

.PATH: ${.CURDIR}/../loader

PROG=		zfsloader
NEWVERSWHAT=	"ZFS enabled bootstrap loader" sparc64
LOADER_ZFS_SUPPORT=yes

.include "${.CURDIR}/../loader/Makefile"
