# $FreeBSD: soc2013/dpl/head/usr.sbin/fifolog/Makefile.inc 201433 2010-01-02 11:07:44Z ed $

LIBFIFOLOG= ${.OBJDIR}/../lib/libfifolog.a

#LINT=	flint
#LINTFLAGS= ${.CURDIR}/../flint.lnt -I/usr/include

.include "../Makefile.inc"
