# $FreeBSD: soc2013/dpl/head/etc/namedb/master/Makefile 170956 2007-06-18 05:44:38Z dougb $

FILES=	empty.db localhost-forward.db localhost-reverse.db

NO_OBJ=
FILESDIR=	/etc/namedb/master
FILESMODE=	644

.include <bsd.prog.mk>
