#	From: @(#)Makefile	8.1 (Berkeley) 6/8/93
# $FreeBSD: soc2013/dpl/head/share/doc/smm/02.config/Makefile 216221 2010-12-04 10:11:20Z uqs $

VOLUME=		smm/02.config
SRCS=		0.t 1.t 2.t 3.t 4.t 5.t 6.t a.t b.t c.t d.t e.t
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
