# $FreeBSD: soc2013/dpl/head/sys/boot/userboot/test/Makefile 223865 2011-06-30 16:08:56Z dfr $


NO_MAN=
WITHOUT_SSP=

.include <bsd.own.mk>

PROG=		test
INTERNALPROG=

CFLAGS+=	-I${.CURDIR}/..
CFLAGS+=	-I${.CURDIR}/../../..

.include <bsd.prog.mk>
