# $FreeBSD: soc2013/dpl/head/sys/modules/drm/sis/Makefile 124515 2004-01-13 11:28:51Z ru $

.PATH:	${.CURDIR}/../../../dev/drm
KMOD= 	sis
SRCS=	sis_drv.c sis_ds.c sis_mm.c
SRCS+=	device_if.h bus_if.h pci_if.h opt_drm.h

.include <bsd.kmod.mk>
