# $FreeBSD: soc2013/dpl/head/kerberos5/libexec/Makefile 233577 2012-03-22 08:48:42Z stas $

SUBDIR=	digest-service ipropd-master ipropd-slave hprop hpropd kadmind kdc \
	kdigest kfd kimpersonate kpasswdd kcm

.include <bsd.subdir.mk>
