# $FreeBSD: soc2013/dpl/head/sys/modules/elink/Makefile 112836 2003-03-29 13:42:20Z mdodd $
#

.PATH:	${.CURDIR}/../../i386/isa

KMOD=		elink
SRCS=		elink.c
EXPORT_SYMS=	elink_reset elink_idseq

.include <bsd.kmod.mk>
