# $FreeBSD: soc2013/dpl/head/sys/modules/md/Makefile 152352 2005-11-11 11:31:23Z pjd $

.PATH: ${.CURDIR}/../../dev/md

KMOD=	geom_md
SRCS=	md.c opt_md.h opt_geom.h vnode_if.h

.include <bsd.kmod.mk>
