# $FreeBSD: soc2013/dpl/head/sys/modules/netgraph/atm/atm/Makefile 193787 2009-06-08 19:57:35Z bz $
#
# Author: Harti Brandt <harti@freebsd.org>
#
.PATH: ${.CURDIR}/../../../../netgraph/atm

KMOD=	ng_atm
SRCS=	ng_atm.c
# CFLAGS+= -DNGATM_DEBUG

.include <bsd.kmod.mk>
