# $FreeBSD: soc2013/dpl/head/sys/modules/mmc/Makefile 163562 2006-10-20 06:52:59Z imp $

.PATH: ${.CURDIR}/../../dev/mmc

KMOD=	mmc
SRCS=	mmc.c mmcbr_if.h mmcbus_if.h device_if.h bus_if.h

.include <bsd.kmod.mk>
