# $FreeBSD: soc2013/dpl/head/sys/modules/re/Makefile 150679 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/re

KMOD=	if_re
SRCS=	if_re.c device_if.h bus_if.h pci_if.h
SRCS+=	miibus_if.h

.include <bsd.kmod.mk>
