# $FreeBSD: soc2013/dpl/head/tools/tools/wtap/wtap/Makefile 233223 2012-03-13 20:30:23Z adrian $

BINDIR?=	/usr/local/bin
PROG=	wtap
SRC=	wtap.c
NO_MAN=	1

CFLAGS+=	-I${.CURDIR}/../../../../sys/dev/wtap/

.include <bsd.prog.mk>
