# $FreeBSD: soc2013/dpl/head/cddl/lib/libumem/Makefile 204640 2010-03-02 19:04:07Z uqs $

.PATH: ${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

LIB=	umem
SRCS=	umem.c
WARNS?=	0
CFLAGS+= -I${.CURDIR}/../../../cddl/compat/opensolaris/lib/libumem

.include <bsd.lib.mk>
