# $FreeBSD: soc2013/dpl/head/gnu/usr.bin/groff/src/utils/tfmtodit/Makefile 114455 2003-05-01 13:22:21Z ru $

PROG_CXX=	tfmtodit
SRCS=		tfmtodit.cpp
DPADD=		${LIBGROFF} ${LIBM}
LDADD=		${LIBGROFF} -lm
CLEANFILES=	${MAN}

.include <bsd.prog.mk>
