# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/rain/Makefile 106802 2002-11-11 10:07:18Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/rain

KMOD=	rain_saver
SRCS=	rain_saver.c

.include <bsd.kmod.mk>
