# $FreeBSD: soc2013/dpl/head/gnu/lib/libstdc++/doc/Makefile 97560 2002-05-29 21:14:48Z obrien $

SRCDIR= ${.CURDIR}/../../../../contrib/libstdc++

.PATH: ${SRCDIR}/../libio

INFO = iostream

INFOENTRY_iostream= "* iostream: (iostream).	The GNU C++ I/O library."

MAKEINFOFLAGS+= -I ${SRCDIR}/../libio 

.include <bsd.info.mk>
