# $FreeBSD: soc2013/dpl/head/sys/modules/i2c/iicbb/Makefile 93066 2002-03-23 15:49:15Z nsouch $

.PATH:		${.CURDIR}/../../../dev/iicbus
KMOD		= iicbb
SRCS		= device_if.h bus_if.h iicbus_if.h \
		  iicbb_if.h iicbb_if.c iicbb.c

.include <bsd.kmod.mk>
