#	from @(#)Makefile.inc	8.1 (Berkeley) 6/4/93
# $FreeBSD: soc2013/dpl/head/lib/libc/db/mpool/Makefile.inc 190541 2009-03-28 07:31:02Z delphij $

.PATH: ${.CURDIR}/db/mpool

SRCS+=	mpool.c mpool-compat.c
