# $FreeBSD: soc2013/dpl/head/tools/regression/usr.bin/make/sysmk/t0/2/1/Makefile 201569 2010-01-04 18:57:22Z obrien $
#
# Can we traverse up to / and find a 'mk/sys.mk'?
#
all:
	@echo ${DASH_M_DOTDOTDOT}
