# Makefile for simple caller of syscall
# $FreeBSD: soc2013/dpl/head/share/examples/kld/syscall/test/Makefile 203392 2010-02-01 16:13:56Z wkoszek $

PROG=	call
NO_MAN=
WARNS?=	5

.include <bsd.prog.mk>
