# $FreeBSD: soc2013/dpl/head/sys/modules/ahb/Makefile 217113 2011-01-06 21:04:00Z imp $

.PATH: ${.CURDIR}/../../dev/ahb

KMOD=	ahb
SRCS=	ahb.c opt_cam.h device_if.h bus_if.h eisa_if.h

.include <bsd.kmod.mk>
