# $FreeBSD: soc2013/dpl/head/secure/lib/Makefile.inc 114326 2003-04-30 07:54:39Z ru $

.include "../Makefile.inc"
.if exists(${.CURDIR}/../../../lib/Makefile.inc)
.include "${.CURDIR}/../../../lib/Makefile.inc"
.endif
