# $FreeBSD: soc2013/dpl/head/sys/modules/bios/smbios/Makefile 204352 2010-02-25 14:13:39Z attilio $
#

.PATH:  ${.CURDIR}/../../../x86/bios

KMOD=	smbios
SRCS=	smbios.c \
	bus_if.h device_if.h

.include <bsd.kmod.mk>
