# $FreeBSD: soc2013/dpl/head/sys/modules/alq/Makefile 206002 2010-03-31 03:58:57Z lstewart $

.include <bsd.own.mk>

.PATH:  ${.CURDIR}/../../kern
KMOD=	alq
SRCS=	opt_mac.h vnode_if.h kern_alq.c

.include <bsd.kmod.mk>
