# $FreeBSD: soc2013/dpl/head/libexec/revnetgroup/Makefile 201423 2010-01-02 09:50:19Z ed $

PROG=	revnetgroup
SRCS=	revnetgroup.c hash.c parse_netgroup.c

MAN= revnetgroup.8

WARNS?=	2

.include <bsd.prog.mk>
