# $FreeBSD: soc2013/dpl/head/sbin/geom/class/mirror/Makefile 216511 2010-12-15 23:24:34Z obrien $

.PATH: ${.CURDIR}/../../misc

GEOM_CLASS=	mirror

DPADD=	${LIBMD}
LDADD=	-lmd

.include <bsd.lib.mk>
