# $FreeBSD: soc2013/dpl/head/sys/modules/ata/atapci/chipsets/ataintel/Makefile 250414 2013-04-06 19:12:49Z marius $

.PATH: ${.CURDIR}/../../../../../dev/ata/chipsets

KMOD=	ataintel
SRCS=	ata-intel.c
SRCS+=	ata_if.h bus_if.h device_if.h pci_if.h

.include <bsd.kmod.mk>
