# $FreeBSD: soc2013/dpl/head/sys/modules/acpi/acpi_dock/Makefile 193573 2009-06-05 18:44:36Z jkim $

.PATH:		${.CURDIR}/../../../dev/acpica
KMOD=		acpi_dock
SRCS=		acpi_dock.c opt_acpi.h device_if.h bus_if.h acpi_if.h
SRCS+=		opt_ddb.h

.include <bsd.kmod.mk>
