# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/green/Makefile 89302 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../../dev/syscons/green

KMOD=	green_saver
SRCS=	green_saver.c

.include <bsd.kmod.mk>
