# $FreeBSD: soc2013/dpl/head/lib/clang/libclangfrontendtool/Makefile 247460 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	clangfrontendtool

SRCDIR=	tools/clang/lib/FrontendTool
SRCS=	ExecuteCompilerInvocation.cpp

TGHDRS=	DiagnosticCommonKinds \
	DiagnosticFrontendKinds \
	Options

.include "../clang.lib.mk"
