# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/blank/Makefile 89302 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../../dev/syscons/blank

KMOD=	blank_saver
SRCS=	blank_saver.c

.include <bsd.kmod.mk>
