# $FreeBSD: soc2013/dpl/head/lib/libcalendar/Makefile 201424 2010-01-02 09:58:07Z ed $

LIB=	calendar

SRCS=	calendar.c easter.c
INCS=	calendar.h

MAN=	calendar.3

MLINKS=	calendar.3 easterg.3 calendar.3 easterog.3 calendar.3 easteroj.3 \
	calendar.3 gdate.3 calendar.3 jdate.3 \
	calendar.3 ndaysg.3 calendar.3 ndaysj.3 \
	calendar.3 week.3 calendar.3 weekday.3

.include <bsd.lib.mk>
