# $FreeBSD: soc2013/dpl/head/sys/modules/acpi/Makefile 238782 2012-07-02 08:31:29Z mav $

SUBDIR=		acpi_asus acpi_asus_wmi acpi_fujitsu acpi_hp acpi_ibm	\
		acpi_panasonic acpi_sony acpi_toshiba acpi_video	\
		acpi_dock acpi_wmi aibs

.include <bsd.subdir.mk>
