# $FreeBSD: soc2013/dpl/head/sys/boot/sparc64/zfsboot/Makefile 235512 2012-05-09 19:08:54Z marius $

.PATH: ${.CURDIR}/../boot1

PROGNAME=	zfsboot
CFLAGS+=	-DZFSBOOT
FILES=		zfsboot

.include "${.CURDIR}/../boot1/Makefile"
