#	$FreeBSD: soc2013/dpl/head/tools/regression/net80211/wep/Makefile 138621 2004-12-08 17:45:53Z sam $

.PATH:	${.CURDIR}/../../../../sys/net80211

KMOD=	test_wep
SRCS+=	test_wep.c

.include <bsd.kmod.mk>
