# $FreeBSD: soc2013/dpl/head/sys/modules/ichwd/Makefile 199058 2009-11-07 11:41:23Z avg $

.PATH: ${.CURDIR}/../../dev/ichwd

KMOD=	ichwd
SRCS=	ichwd.c device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
