#!/bin/sh
#
# $FreeBSD: soc2013/dpl/head/etc/rc.d/DAEMON 174481 2007-12-08 07:20:23Z dougb $
#

# PROVIDE: DAEMON
# REQUIRE: NETWORKING SERVERS

#	This is a dummy dependency, to ensure that general purpose daemons
#	are run _after_ the above are.
