#!/bin/sh
#
# $FreeBSD: soc2013/dpl/head/etc/rc.d/ftp-proxy 230381 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: ftp-proxy
# REQUIRE: DAEMON pf
# KEYWORD: shutdown

. /etc/rc.subr

name="ftpproxy"
rcvar="ftpproxy_enable"
command="/usr/sbin/ftp-proxy"

load_rc_config $name
run_rc_command "$1"
