#!/bin/sh
#
# $FreeBSD: soc2013/dpl/head/etc/rc.d/kfd 235410 2012-05-06 20:46:04Z stas $
#

# PROVIDE: kfd
# REQUIRE: NETWORK
# KEYWORD: shutdown

. /etc/rc.subr

name=kfd
rcvar=kfd_enable
load_rc_config $name
command_args="-i &"

run_rc_command "$1"
