#!/bin/sh
#
# $FreeBSD: soc2013/dpl/head/etc/rc.d/LOGIN 231832 2012-02-12 07:45:48Z ed $
#

# PROVIDE: LOGIN
# REQUIRE: DAEMON utx

#	This is a dummy dependency to ensure user services such as xdm,
#	inetd, cron and kerberos are started after everything else, in case
#	the administrator has increased the system security level and
#	wants to delay user logins until the system is (almost) fully
#	operational.
