#!/bin/sh
#
# $FreeBSD: soc2013/dpl/head/etc/rc.d/mroute6d 230381 2012-01-14 02:18:41Z dougb $
#

# PROVIDE: mroute6d
# REQUIRE: netif routing
# BEFORE: NETWORKING
# KEYWORD: nojail

. /etc/rc.subr

name="mroute6d"
rcvar="mroute6d_enable"
command="/usr/local/sbin/pim6dd"

load_rc_config $name
run_rc_command "$1"
