#	@(#)Makefile	1.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.bin/ktrace/Makefile 226784 2011-10-18 08:26:12Z des $

PROG=	ktrace
SRCS=	ktrace.c subr.c
MLINKS= ktrace.1 trace.1 

.include <bsd.prog.mk>
