# $FreeBSD: soc2013/dpl/head/sys/modules/ipmi/ipmi_linux/Makefile 190495 2009-03-26 19:15:31Z ambrisko $

.PATH: ${.CURDIR}/../../../dev/ipmi

KMOD=	ipmi_linux
SRCS=	ipmi_linux.c

.include <bsd.kmod.mk>
