# $FreeBSD: soc2013/dpl/head/share/i18n/esdb/APPLE/Makefile 219062 2011-02-25 00:04:39Z gabor $
# $NetBSD: Makefile.inc,v 1.2 2008/10/25 22:27:35 apb Exp $

CODE=	MAC
ESUBDIR= APPLE
SED_EXP= 's/changeme/%%PART%%/'
NO_SEP=	yes

.include "../Makefile.part"
