#	from: @(#)Makefile	5.2 (Berkeley) 5/11/90
# $FreeBSD: soc2013/dpl/head/usr.bin/rpcinfo/Makefile 201429 2010-01-02 10:27:05Z ed $

PROG=	rpcinfo
SRCS=	rpcinfo.c
MAN=	rpcinfo.8

CFLAGS+= -DPORTMAP

WARNS?=	2

.include <bsd.prog.mk>
