#	$OpenBSD: Makefile,v 1.1 1997/01/26 02:23:20 millert Exp $
# $FreeBSD: soc2013/dpl/head/sbin/fsirand/Makefile 208117 2010-05-14 14:26:49Z uqs $

PROG=	fsirand
MAN=	fsirand.8
WARNS?=	3
DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
