#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.sbin/vipw/Makefile 201433 2010-01-02 11:07:44Z ed $

PROG=	vipw
MAN=	vipw.8

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.prog.mk>
