# $FreeBSD: soc2013/dpl/head/usr.bin/clang/llvm-as/Makefile 250624 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-as

SRCDIR=	tools/llvm-as
SRCS=	llvm-as.cpp

LIBDEPS=llvmbitwriter \
	llvmasmparser \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
