#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.bin/vis/Makefile 249504 2013-03-15 00:05:50Z brooks $

PROG=	vis
SRCS=	vis.c foldit.c

.PATH: ${.CURDIR}/../../contrib/vis
CFLAGS+=	-I${.CURDIR}/../../contrib/vis

.include <bsd.prog.mk>
