# $FreeBSD: soc2013/dpl/head/tools/regression/mac/mac_bsdextended/Makefile 145184 2005-04-16 12:06:40Z rwatson $

PROG=	test_ugidfw
DPADD=	${LIBUGIDFW}
LDADD=	-lugidfw
NO_MAN=

.include <bsd.prog.mk>
