# $FreeBSD: soc2013/dpl/head/sys/modules/ata/atacard/Makefile 250414 2013-04-06 19:12:49Z marius $

.PATH: ${.CURDIR}/../../../dev/ata

KMOD=	atacard
SRCS=	ata-card.c
SRCS+=	ata_if.h bus_if.h card_if.h device_if.h pccarddevs.h

.include <bsd.kmod.mk>
