# $Id: Makefile,v 1.6 2003/08/14 20:05:58 max Exp $
# $FreeBSD: soc2013/dpl/head/usr.sbin/bluetooth/bcmfw/Makefile 140984 2005-01-28 16:08:11Z ru $

PROG=		bcmfw
MAN=		bcmfw.8
WARNS?=		2

.include <bsd.prog.mk>
