# $FreeBSD: soc2013/dpl/head/sys/modules/netgraph/vjc/Makefile 89302 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.1 1999/01/24 06:48:07 archie Exp $

.PATH: ${.CURDIR}/../../../net

KMOD=	ng_vjc
SRCS= 	ng_vjc.c slcompress.c

.include <bsd.kmod.mk>
