# $FreeBSD: soc2013/dpl/head/sys/modules/ata/ataisa/Makefile 250414 2013-04-06 19:12:49Z marius $

.PATH: ${.CURDIR}/../../../dev/ata

KMOD=	ataisa
SRCS=	ata-isa.c
SRCS+=	ata_if.h bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
