# $FreeBSD: soc2013/dpl/head/sys/modules/ahci/Makefile 239803 2012-07-26 13:44:48Z mav $

.PATH: ${.CURDIR}/../../dev/ahci

KMOD=	ahci
SRCS=	ahci.c ahciem.c ahci.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
