# $FreeBSD: soc2013/dpl/head/tools/regression/pthread/mutex_isowned_np/Makefile 204354 2010-02-25 14:42:26Z ru $

PROG=	mutex_isowned_np
NO_MAN=
DPADD=	${LIBPTHREAD}
LDADD=	-lpthread

.include <bsd.prog.mk>
