# $FreeBSD: soc2013/dpl/head/sys/modules/netgraph/lmi/Makefile 89302 2002-01-11 15:49:02Z ru $
# $Whistle: Makefile,v 1.1 1999/01/19 19:39:21 archie Exp $

KMOD=	ng_lmi
SRCS= 	ng_lmi.c

.include <bsd.kmod.mk>
