# $FreeBSD: soc2013/dpl/head/sys/modules/msdosfs_iconv/Makefile 120535 2003-09-26 20:26:25Z fjoe $

.PATH:	${.CURDIR}/../../fs/msdosfs
KMOD=	msdosfs_iconv
SRCS=	msdosfs_iconv.c

.include <bsd.kmod.mk>
