# $FreeBSD: soc2013/dpl/head/lib/clang/libllvmmcdisassembler/Makefile 250624 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

LIB=	llvmmcdisassembler

SRCDIR=	lib/MC/MCDisassembler
SRCS=	Disassembler.cpp

.include "../clang.lib.mk"
