#	$NetBSD: Makefile,v 1.4 1999/05/11 21:02:25 augustss Exp $
# $FreeBSD: soc2013/dpl/head/usr.bin/usbhidctl/Makefile 94787 2002-04-15 09:33:34Z ru $

PROG=	usbhidctl
SRCS=	usbhid.c
DPADD=	${LIBUSBHID}
LDADD=	-lusbhid

.include <bsd.prog.mk>
