#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.bin/unifdef/Makefile 201429 2010-01-02 10:27:05Z ed $

PROG=	unifdef
SCRIPTS=unifdefall.sh
MLINKS=	unifdef.1 unifdefall.1

.include <bsd.prog.mk>
