# $FreeBSD: soc2013/dpl/head/sys/modules/acl_posix1e/Makefile 233220 2012-03-13 20:28:42Z adrian $

.include <bsd.own.mk>

.PATH:  ${.CURDIR}/../../kern
KMOD=	acl_posix1e
SRCS=	vnode_if.h subr_acl_posix1e.c

.include <bsd.kmod.mk>
