# $FreeBSD: soc2013/dpl/head/sys/modules/cpsw/Makefile 240379 2012-08-15 06:31:32Z gonzo $

.PATH: ${.CURDIR}/../../arm/ti/cpsw

KMOD=   if_cpsw
SRCS=   if_cpsw.c device_if.h bus_if.h ofw_bus_if.h miibus_if.h

.include <bsd.kmod.mk>
