#	@(#)Makefile	8.1 (Berkeley) 6/5/93
# $FreeBSD: soc2013/dpl/head/sbin/dmesg/Makefile 198279 2009-10-19 16:00:24Z ru $

PROG=	dmesg
MAN=	dmesg.8

LDADD=	-lkvm
DPADD=	${LIBKVM}

.include <bsd.prog.mk>
