# $Id: Makefile,v 1.2 2003/10/21 22:22:27 max Exp $
# $FreeBSD: soc2013/dpl/head/etc/bluetooth/Makefile 151368 2005-10-14 15:26:23Z ru $

FILESDIR=		/etc/bluetooth
FILES=			hcsecd.conf hosts protocols
FILESMODE_hcsecd.conf=	600
FILESMODE_hosts=	644

.include <bsd.prog.mk>
