# $FreeBSD: soc2013/dpl/head/sys/modules/aha/Makefile 217113 2011-01-06 21:04:00Z imp $

.PATH: ${.CURDIR}/../../dev/aha

KMOD=	aha
SRCS=	aha.c aha_isa.c ahareg.h opt_cam.h device_if.h bus_if.h \
	isa_if.h

.include <bsd.kmod.mk>
