# $FreeBSD: soc2013/dpl/head/sys/modules/amdsbwd/Makefile 200012 2009-11-30 11:44:03Z avg $

.PATH:  ${.CURDIR}/../../dev/amdsbwd
KMOD    = amdsbwd
SRCS    = amdsbwd.c
SRCS    += device_if.h bus_if.h pci_if.h isa_if.h

.include <bsd.kmod.mk>
