# $FreeBSD: soc2013/dpl/head/sbin/mdmfs/Makefile 198279 2009-10-19 16:00:24Z ru $

PROG=		mdmfs
LINKS=		${BINDIR}/${PROG} ${BINDIR}/mount_mfs
MAN=		mdmfs.8
MLINKS+=	mdmfs.8 mount_mfs.8

.include <bsd.prog.mk>
