# $FreeBSD: soc2013/dpl/head/usr.sbin/ctm/ctm_smail/Makefile 201433 2010-01-02 11:07:44Z ed $

.PATH: ${.CURDIR}/../ctm_rmail

PROG=	ctm_smail
NO_MAN=
SRCS=	ctm_smail.c error.c

CFLAGS+= -I${.CURDIR}/../ctm_rmail

WARNS?=	2

.include <bsd.prog.mk>
