# $FreeBSD: soc2013/dpl/head/lib/libiconv_modules/BIG5/Makefile 219062 2011-02-25 00:04:39Z gabor $

SHLIB=	BIG5
SRCS+=	citrus_big5.c
CFLAGS+= --param max-inline-insns-single=32

.include <bsd.lib.mk>
