# $FreeBSD: soc2013/dpl/head/sbin/geom/class/part/Makefile 216511 2010-12-15 23:24:34Z obrien $

.PATH: ${.CURDIR}/../../misc

GEOM_CLASS=	part

DPADD=	${LIBUTIL}
LDADD=	-lutil

.include <bsd.lib.mk>
