# $FreeBSD: soc2013/dpl/head/lib/libiconv_modules/GBK2K/Makefile 219062 2011-02-25 00:04:39Z gabor $

SHLIB=	GBK2K
SRCS+=	citrus_gbk2k.c
CFLAGS+= --param max-inline-insns-single=16

.include <bsd.lib.mk>
