# $FreeBSD: soc2013/dpl/head/gnu/usr.bin/diff/doc/Makefile 170801 2007-06-15 07:09:34Z delphij $

INFO = diff

INFOENTRY_diff= "* DIFF: (diff).                 DIFF/PATCH Reference Manual."

SRCDIR=${.CURDIR}/../../../../contrib/diff/doc

.include <bsd.info.mk>
