# $FreeBSD: soc2013/dpl/head/sys/modules/pmc/Makefile 146092 2005-05-10 12:02:18Z nyan $

.PATH: ${.CURDIR}/../../pc98/cbus

KMOD=	pmc
SRCS=	pmc.c
SRCS+=	bus_if.h device_if.h isa_if.h

.include <bsd.kmod.mk>
