# $FreeBSD: soc2013/dpl/head/usr.sbin/pc-sysinstall/backend-partmanager/Makefile 209570 2010-06-25 22:35:19Z imp $

FILES=	create-part.sh delete-part.sh
FILESMODE=	${BINMODE}
FILESDIR=${SHAREDIR}/pc-sysinstall/backend-partmanager
NO_OBJ=

.include <bsd.prog.mk>
