# $FreeBSD: soc2013/dpl/head/lib/clang/libllvminterpreter/Makefile 247460 2013-02-02 22:28:29Z dim $

.include <bsd.own.mk>

LIB=	llvminterpreter

SRCDIR=	lib/ExecutionEngine/Interpreter
SRCS=	Execution.cpp \
	ExternalFunctions.cpp \
	Interpreter.cpp \

TGHDRS=	Intrinsics

.include "../clang.lib.mk"
