#	@(#)Makefile	8.1 (Berkeley) 5/31/93
# $FreeBSD: soc2013/dpl/head/games/primes/Makefile 139146 2004-12-21 08:47:35Z ru $

PROG=	primes
SRCS=	pattern.c pr_tbl.c primes.c
NO_MAN=
DPADD=	${LIBM}
LDADD=	-lm

.include <bsd.prog.mk>
