# $FreeBSD: soc2013/dpl/head/sys/modules/nfs_common/Makefile 204011 2010-02-16 20:00:21Z marius $

.PATH: ${.CURDIR}/../../nfs

KMOD=	nfs_common
SRCS=	nfs_common.c opt_nfs.h vnode_if.h

.include <bsd.kmod.mk>
