# $FreeBSD: soc2013/dpl/head/sys/modules/acpi/acpi_rapidstart/Makefile 251564 2013-05-08 12:53:21Z takawata $

.PATH:		${.CURDIR}/../../../dev/acpi_support

KMOD=		acpi_rapidstart
SRCS=		acpi_rapidstart.c opt_acpi.h device_if.h bus_if.h acpi_if.h

.include <bsd.kmod.mk>
