# Makefile for kld char device driver.
# $FreeBSD: soc2013/dpl/head/share/examples/kld/cdev/module/Makefile 118428 2003-08-03 10:39:29Z mbr $

KMOD=	cdev
SRCS=	cdev.c cdevmod.c

.include <bsd.kmod.mk>
