# $FreeBSD: soc2013/dpl/head/sys/modules/s3/Makefile 72037 2001-02-04 12:35:22Z peter $

.PATH: ${.CURDIR}/../../dev/fb

KMOD=	s3
SRCS=	device_if.h bus_if.h isa_if.h pci_if.h \
	s3_pci.c

.include <bsd.kmod.mk>
