# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/fire/Makefile 106805 2002-11-11 10:11:59Z mux $

.PATH:	${.CURDIR}/../../../dev/syscons/fire

KMOD=	fire_saver
SRCS=	fire_saver.c

.include <bsd.kmod.mk>
