# $FreeBSD: soc2013/dpl/head/sys/modules/mac_ifoff/Makefile 105768 2002-10-22 17:10:15Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_ifoff

KMOD=	mac_ifoff
SRCS=	vnode_if.h \
	mac_ifoff.c

.include <bsd.kmod.mk>
