# $FreeBSD: soc2013/dpl/head/sys/modules/khelp/h_ertt/Makefile 217849 2011-01-24 23:08:38Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/khelp
KMOD=	h_ertt
SRCS=	h_ertt.c

.include <bsd.kmod.mk>
