# $FreeBSD: soc2013/dpl/head/gnu/usr.bin/cvs/doc/Makefile 146972 2005-06-03 15:08:30Z imp $

.include "${.CURDIR}/../Makefile.inc"

SRCDIR= ${CVSDIR}/doc

INFO=	cvs cvsclient
INFOSECTION= "Programming & development tools."
INFOENTRY_cvs= "* CVS: (cvs).			CVS Reference Manual."
INFOENTRY_cvsclient= "* CVS-CLIENT: (cvsclient).	CVS client/server Reference Manual."

.include <bsd.info.mk>
