# $FreeBSD: soc2013/dpl/head/sys/modules/firmware/Makefile 178375 2008-04-20 16:11:14Z antoine $

.PATH: ${.CURDIR}/../../kern

KMOD=	firmware
SRCS=	subr_firmware.c vnode_if.h

.include <bsd.kmod.mk>
