#
# $FreeBSD: soc2013/dpl/head/usr.sbin/pmccontrol/Makefile 201433 2010-01-02 11:07:44Z ed $
#

PROG=	pmccontrol
MAN=	pmccontrol.8

DPADD=	${LIBPMC}
LDADD=	-lpmc

SRCS=	pmccontrol.c

.include <bsd.prog.mk>
