# $FreeBSD: soc2013/dpl/head/usr.bin/mkesdb/Makefile 252144 2013-05-23 18:07:01Z ed $

.PATH: ${.CURDIR}/../../lib/libc/iconv

PROG=	mkesdb
LDFLAGS+= -L${.OBJDIR}/../../lib/libc

NO_WMISSING_VARIABLE_DECLARATIONS=

.include "${.CURDIR}/Makefile.inc"
.include <bsd.prog.mk>
