# $FreeBSD: soc2013/dpl/head/sys/modules/epic/Makefile 202049 2010-01-10 15:44:48Z marius $

.PATH: ${.CURDIR}/../../sparc64/ebus

KMOD=	epic
SRCS=	device_if.h epic.c bus_if.h ofw_bus_if.h

.include <bsd.kmod.mk>
