#	From: @(#)Makefile	8.2 (Berkeley) 2/28/94
# $FreeBSD: soc2013/dpl/head/share/doc/smm/08.sendmailop/Makefile 136953 2004-10-24 15:33:08Z ru $

VOLUME=		smm/08.sendmailop
SRCS=		op.me
MACROS=		-me
USE_PIC=
USE_EQN=
SRCDIR=		${.CURDIR}/../../../../contrib/sendmail/doc/op

.include <bsd.doc.mk>
