# $FreeBSD: soc2013/dpl/head/sys/modules/rndtest/Makefile 112146 2003-03-11 19:26:16Z sam $

.PATH:	${.CURDIR}/../../dev/rndtest
KMOD	= rndtest
SRCS	= rndtest.c
SRCS   += device_if.h bus_if.h

.include <bsd.kmod.mk>
