# $FreeBSD: soc2013/dpl/head/gnu/usr.bin/groff/src/utils/Makefile 75633 2001-04-17 12:37:18Z ru $

SUBDIR=		addftinfo afmtodit hpftodit indxbib lkbib lookbib pfbtops tfmtodit

.include <bsd.subdir.mk>
