# $FreeBSD: soc2013/dpl/head/sys/modules/mac_lomac/Makefile 193631 2009-06-06 17:01:44Z rwatson $

.PATH: ${.CURDIR}/../../security/mac_lomac

KMOD=	mac_lomac
SRCS=	vnode_if.h \
	mac_lomac.c

.include <bsd.kmod.mk>
