# $FreeBSD: soc2013/dpl/head/lib/libnetbsd/Makefile 245755 2012-12-21 20:37:38Z brooks $

.include <bsd.own.mk>

LIB=	netbsd

CFLAGS+=	-I${.CURDIR}

SRCS+=	strsuftoll.c util.c util.h

INTERNALLIB=

.include <bsd.lib.mk>
