# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/star/Makefile 106540 2002-11-06 13:47:00Z nyan $

.PATH:	${.CURDIR}/../../../dev/syscons/star

KMOD=	star_saver
SRCS=	star_saver.c

.include <bsd.kmod.mk>
