# $FreeBSD: soc2013/dpl/head/sys/modules/i2c/controllers/lpbb/Makefile 116392 2003-06-14 20:43:33Z jmg $

.PATH:		${.CURDIR}/../../../../dev/ppbus
KMOD		= lpbb
SRCS		= device_if.h bus_if.h iicbb_if.h ppbus_if.h \
		  lpbb.c

.include <bsd.kmod.mk>
