# $FreeBSD: soc2013/dpl/head/usr.sbin/bsdconfig/mouse/include/Makefile 239365 2012-07-14 03:16:57Z dteske $

NO_OBJ=

FILESDIR=	${LIBEXECDIR}/bsdconfig/110.mouse/include
FILES=		messages.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
