# $FreeBSD: soc2013/dpl/head/sys/modules/txp/Makefile 150679 2005-09-27 18:10:43Z mlaier $

.PATH: ${.CURDIR}/../../dev/txp

KMOD=	if_txp
SRCS=	if_txp.c device_if.h bus_if.h pci_if.h

.include <bsd.kmod.mk>
