# $FreeBSD: soc2013/dpl/head/lib/libalias/modules/Makefile 162744 2006-09-27 12:30:27Z ru $

.include "${.CURDIR}/../../../sys/modules/libalias/modules/modules.inc"

SUBDIR=	${MODULES}

.include <bsd.subdir.mk>
