# $FreeBSD: soc2013/dpl/head/sys/modules/siis/Makefile 195844 2009-07-21 12:32:46Z mav $

.PATH: ${.CURDIR}/../../dev/siis

KMOD=	siis
SRCS=	siis.c siis.h device_if.h bus_if.h pci_if.h opt_cam.h

.include <bsd.kmod.mk>
