#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.bin/unvis/Makefile 249504 2013-03-15 00:05:50Z brooks $

PROG=	unvis

.PATH: ${.CURDIR}/../../contrib/unvis

.include <bsd.prog.mk>
