#	@(#)Makefile	8.1 (Berkeley) 6/6/93
# $FreeBSD: soc2013/dpl/head/usr.bin/wall/Makefile 202243 2010-01-13 18:09:54Z ed $

PROG=	wall
SRCS=	ttymsg.c wall.c
BINGRP=	tty
BINMODE=2555

.include <bsd.prog.mk>
