# $FreeBSD: soc2013/dpl/head/tools/tools/netrate/tcpp/Makefile 204628 2010-03-02 16:58:04Z uqs $

PROG=	tcpp
INCS=	tcpp.h
NO_MAN=	
SRCS=	tcpp.c tcpp_client.c tcpp_server.c tcpp_util.c
WARNS?=	3

.include <bsd.prog.mk>
