# $OpenBSD: Makefile,v 1.1 2004/04/26 19:51:20 markus Exp $
# $FreeBSD: soc2013/dpl/head/usr.sbin/tcpdrop/Makefile 201433 2010-01-02 11:07:44Z ed $

PROG=	tcpdrop
MAN=	tcpdrop.8

.include <bsd.prog.mk>
