# $FreeBSD: soc2013/dpl/head/sys/modules/wpi/Makefile 237002 2012-06-03 12:19:16Z uqs $

.PATH:  ${.CURDIR}/../../dev/wpi

KMOD    = if_wpi
SRCS    = if_wpi.c device_if.h bus_if.h pci_if.h opt_wlan.h

.include <bsd.kmod.mk>
