# $FreeBSD: soc2013/dpl/head/share/doc/legal/intel_iwn/Makefile 208631 2010-05-27 08:21:52Z rpaulo $

NO_OBJ=
FILES=		${.CURDIR}/../../../../sys/contrib/dev/iwn/LICENSE
FILESDIR=	${SHAREDIR}/doc/legal/intel_iwn

.include <bsd.prog.mk>
