# $FreeBSD: soc2013/dpl/head/sys/modules/geom/geom_mbr/Makefile 117297 2003-07-05 08:11:43Z jmg $

.PATH: ${.CURDIR}/../../../geom

KMOD=	geom_mbr
SRCS=	geom_mbr.c geom_mbr_enc.c

.include <bsd.kmod.mk>
