# $FreeBSD: soc2013/dpl/head/sys/modules/sge/Makefile 206668 2010-04-14 20:45:33Z yongari $

.PATH: ${.CURDIR}/../../dev/sge

KMOD=	if_sge
SRCS=	if_sge.c device_if.h bus_if.h pci_if.h miibus_if.h

.include <bsd.kmod.mk>
