#	From: @(#)Makefile	5.3 (Berkeley) 6/8/93
# $FreeBSD: soc2013/dpl/head/share/doc/papers/fsinterface/Makefile 105960 2002-10-25 08:10:40Z ru $

VOLUME=	papers
DOC=	fsinterface
SRCS=	fsinterface.ms
MACROS=	-ms

.include <bsd.doc.mk>
