# $FreeBSD: soc2013/dpl/head/gnu/usr.bin/texinfo/install-info/Makefile 97895 2002-06-05 06:58:33Z ru $

PROG=	install-info

DPADD=	${LIBTXI}
LDADD=	${LIBTXI}

.include <bsd.prog.mk>

.PATH:	${TXIDIR}/util ${TXIDIR}/doc
