# $FreeBSD: soc2013/dpl/head/sys/modules/cc/cc_cubic/Makefile 216157 2010-12-02 06:05:44Z lstewart $

.include <bsd.own.mk>

.PATH: ${.CURDIR}/../../../netinet/cc
KMOD=	cc_cubic
SRCS=	cc_cubic.c

.include <bsd.kmod.mk>
