# $FreeBSD: soc2013/dpl/head/usr.bin/clang/llvm-bcanalyzer/Makefile 250624 2013-04-12 17:57:40Z dim $

.include <bsd.own.mk>

PROG_CXX=llvm-bcanalyzer

SRCDIR=	tools/llvm-bcanalyzer
SRCS=	llvm-bcanalyzer.cpp

LIBDEPS=llvmbitreader \
	llvmcore \
	llvmsupport

.include "../clang.prog.mk"
