# $FreeBSD: soc2013/dpl/head/usr.sbin/bsdconfig/password/share/Makefile 241856 2012-09-18 22:28:42Z dteske $

NO_OBJ=

FILESDIR=	${SHAREDIR}/bsdconfig/password
FILES=		password.subr

beforeinstall:
	mkdir -p ${DESTDIR}${FILESDIR}

.include <bsd.prog.mk>
