# $FreeBSD: soc2013/dpl/head/tools/tools/hcomp/Makefile 118468 2003-08-04 13:10:01Z des $

BINDIR		?= ${HOME}/bin
BINOWN		?= ${USER}
BINGRP		?= ${USER}
SCRIPTS		 = hcomp.pl

MANDIR		?= ${HOME}/man/man
MANOWN		?= ${USER}
MANGRP		?= ${USER}
MAN		 = # empty

.include <bsd.prog.mk>
