# $FreeBSD: soc2013/dpl/head/sys/modules/syscons/fade/Makefile 89302 2002-01-11 15:49:02Z ru $

.PATH:	${.CURDIR}/../../../dev/syscons/fade

KMOD=	fade_saver
SRCS=	fade_saver.c

.include <bsd.kmod.mk>
