# $FreeBSD: soc2013/dpl/head/secure/lib/libcrypto/engines/Makefile 239316 2012-07-12 19:30:53Z jkim $

SUBDIR=	lib4758cca libaep libatalla libchil libcswift libgost libnuron \
	libsureware libubsec

.include <bsd.subdir.mk>
